// Generated by CoffeeScript 1.6.3
var count, low_x, low_y, low_z, worker_data;

low_x = 0;

low_y = 0;

low_z = 0;

count = 0;

worker_data = {};

self.onmessage = function(event) {
  var high_x, high_y, high_z, mag, post_data, temp_x, temp_y, temp_z;
  post_data = event.data;
  temp_x = post_data["x"] / 9.8;
  temp_y = post_data["y"] / 9.8;
  temp_z = post_data["z"] / 9.8;
  low_x = temp_x * 0.1 + low_x * (1.0 - 0.1);
  low_y = temp_y * 0.1 + low_y * (1.0 - 0.1);
  low_z = temp_z * 0.1 + low_z * (1.0 - 0.1);
  high_x = temp_x - low_x;
  high_y = temp_y - low_y;
  high_z = temp_z - low_z;
  mag = Math.sqrt(high_x * high_x + high_y * high_y + high_z * high_z);
  worker_data = {
    amag: mag,
    time: post_data["time"],
    currenttime: post_data["currenttime"]
  };
  if (mag >= 0.2) {
    return self.postMessage(worker_data);
  }
};
