/* Create Tables */



CREATE TABLE LAUGH_DATA
(
	ID BIGINT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
	NODE_ID VARCHAR(200) NOT NULL,
	VIDEOID VARCHAR(200),
	PLAYTIME DOUBLE UNSIGNED NOT NULL,
	AMAG DOUBLE NOT NULL,
	DATE VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE VIDEO_DATA
(
	ID BIGINT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
	VIDEOID VARCHAR(100) NOT NULL UNIQUE,
	PLAY BIGINT UNSIGNED,
	LAUGH_SUM BIGINT UNSIGNED NOT NULL,
	DATE DATETIME NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE USER_DATA
(
	ID BIGINT UNSIGNED NOT NULL UNIQUE AUTO_INCREMENT,
	NODE_ID VARCHAR(200),
	CLIENT_ID VARCHAR(200) NOT NULL,
	REMOTE_ADDRES VARCHAR(100) NOT NULL,
	USER_AGENT VARCHAR(200) NOT NULL,
	LOGIN DATETIME NOT NULL,
	PRIMARY KEY (ID)
);

create table sample_data
(
id INT(11) NOT NULL AUTO_INCREMENT,
sample VARCHAR(255),
sample2 VARCHAR(255),
PRIMARY KEY(id)
);